import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>VexBook</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <h1>Lets build facebook</h1>
     
    </div>
  )
}
