import Head from 'next/head'
import Feed from '../components/Feed'
import Header from '../components/Header'
import SideBar from '../components/SideBar'

export default function Home() {
  return (
    <div className="bg-gray-100">
      <Head>
        <title>VexBook</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="https://upload.wikimedia.org/wikipedia/commons/0/05/Facebook_Logo_%282019%29.png" />
      </Head>

      <Header/>

      <main className="flex">
        <SideBar/>
        <Feed/>
        {/* Widgets */}
      </main>
     
    </div>
  )
}
